### ISSUE TITLE
taskwarrior calendar support

### ISSUE THREAD

**Issue by linuxcaffe** [huantrinh1802/khal_endar.nvim#3]
Just a crazy idea. Taskwarrior has a calendar command, but it would be great to be able to easily generate calendars and agendas from taskwarrior due, sched, wait or until dated tasks ESPECIALLY if that generated calendar was in khal format!

( super extra bonus points if those calendars could also be made to appear in m_taskwarrior_d.nvim)

**Comment by huantrinh1802** [comment]
Hey @linuxcaffe, thanks for the idea. I don't think that feature would fit into neither of the plugins. Have you considered using [Syncall](https://github.com/bergercookie/syncall/)? 

Even though I don't use syncall but I wrote my own Python script to generate iCal items using [iCalendar lib](https://pypi.org/project/icalendar/)

**Comment by linuxcaffe** [comment]
Alright @huantrinh1802 , thanks for the quick response, the brilliant code and the awesome links!
